final hostUrl = "http://backend.sec2hand.com/";
final baseUrl = "http://backend.sec2hand.com/api/";
final customerRegisterApi = baseUrl+"customer-register";
final dealerRegisterApi = baseUrl+"dealer-register";
final customerLoginApi = baseUrl+"customer-login";
final dealerLoginApi = baseUrl+"dealer-login";
final dealerListApi = baseUrl+"dealer-filter";
final profileApi = baseUrl+"profile";
final postListApi = baseUrl+"post-list";
final productListApi = baseUrl+"product-list";
final likeApi = baseUrl+"post-like";
final postAddApi = baseUrl+"post-create";
final productAddApi = baseUrl+"product-create";
final bikeAddApi = baseUrl+"bike-create";
final carAddApi = baseUrl+"car-create";
final mobileAddApi = baseUrl+"mobile-create";
final profileEditApi = baseUrl+"profile-edit";
final profileCustomerEditApi = baseUrl+"customer-profile-edit";
final commentApi = baseUrl+"post-comment-create";
final commentListApi = baseUrl+"post-comment-list";
final postDetailApi = baseUrl+"post-detail/";
final productDetailApi = baseUrl+"item-detail/";
final dealerDetailApi = baseUrl+"dealer/";
final sendOtpApi = baseUrl+"send-otp";
final verifyOtpApi = baseUrl+"verify-otp";
final verifyCustomerOtpApi = baseUrl+"customer-verify-otp";
final changePasswordApi = baseUrl+"change-password";
final cityListApi = baseUrl+"city-list";
final brandListApi = baseUrl+"brand-list";
var profileData;
var token="";
var usernameData;
var cityListData;